import { createInsertSchema, createSelectSchema, createUpdateSchema } from "drizzle-zod";
import { z } from "zod";

import { users } from "@/lib/drizzle/schema";

/**
 * User validation.
 *
 * Derived from the table definition with drizzle-zod, so the M02 requirement
 * that "validation must match the database schema" holds by construction rather
 * than by review. Adding a column changes these schemas automatically; a
 * hand-written mirror would silently fall out of step.
 *
 * Refinements below add what the database cannot express.
 */

export const userSelectSchema = createSelectSchema(users);

export const userInsertSchema = createInsertSchema(users, {
  /*
   * Not generated by the database. ADR-005 Decision 3: this must be the id of an
   * existing auth.users row, so the caller always supplies it.
   */
  id: z.string().uuid("id must be the UUID of an existing Supabase Auth user"),
  name: z.string().trim().min(1, "Name is required").max(120),
  email: z
    .string()
    .trim()
    .toLowerCase()
    .min(1, "Email is required")
    .email("Enter a valid email address"),
}).omit({
  /* Owned by the database and the soft-delete flow, never by a caller. */
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
});

export const userUpdateSchema = createUpdateSchema(users, {
  name: z.string().trim().min(1, "Name is required").max(120),
  email: z.string().trim().toLowerCase().email("Enter a valid email address"),
})
  .omit({
    /* Immutable: id is the Supabase Auth identity. */
    id: true,
    createdAt: true,
    updatedAt: true,
    deletedAt: true,
  })
  /* An update with no fields is a caller bug, not a no-op to be swallowed. */
  .refine((value) => Object.keys(value).length > 0, {
    message: "An update must change at least one field",
  });

export type UserSelect = z.infer<typeof userSelectSchema>;
export type UserInsert = z.infer<typeof userInsertSchema>;
export type UserUpdate = z.infer<typeof userUpdateSchema>;
