import { createInsertSchema, createSelectSchema, createUpdateSchema } from "drizzle-zod";
import { z } from "zod";

import { loginHistory, users } from "@/lib/drizzle/schema";

/**
 * User validation.
 *
 * Derived from the table definition with drizzle-zod, so the M02 requirement
 * that "validation must match the database schema" holds by construction rather
 * than by review. Adding a column changes these schemas automatically; a
 * hand-written mirror would silently fall out of step.
 *
 * Refinements below add what the database cannot express.
 */

export const userSelectSchema = createSelectSchema(users);

export const userInsertSchema = createInsertSchema(users, {
  /*
   * Not generated by the database. ADR-005 Decision 3: this must be the id of an
   * existing auth.users row, so the caller always supplies it.
   */
  id: z.string().uuid("id must be the UUID of an existing Supabase Auth user"),
  name: z.string().trim().min(1, "Name is required").max(120),
  email: z
    .string()
    .trim()
    .toLowerCase()
    .min(1, "Email is required")
    .email("Enter a valid email address"),
}).omit({
  /* Owned by the database and the soft-delete flow, never by a caller. */
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
});

/*
 * Every refinement is `.optional()`. Supplying a schema to createUpdateSchema
 * replaces the generated one entirely, including its optionality — without this,
 * a partial update would be forced to resend every refined field.
 */
export const userUpdateSchema = createUpdateSchema(users, {
  name: z.string().trim().min(1, "Name is required").max(120).optional(),
  email: z.string().trim().toLowerCase().email("Enter a valid email address").optional(),
})
  .omit({
    /* Immutable: id is the Supabase Auth identity. */
    id: true,
    createdAt: true,
    updatedAt: true,
    deletedAt: true,
  })
  /* An update with no fields is a caller bug, not a no-op to be swallowed. */
  .refine((value) => Object.keys(value).length > 0, {
    message: "An update must change at least one field",
  });

/**
 * Login history insert.
 *
 * Derived from the table so it cannot drift. `failureReason` is capped and must
 * never carry a password, a token, or anything a caller received from the user.
 */
export const loginHistoryInsertSchema = createInsertSchema(loginHistory, {
  email: z.string().trim().max(320).optional(),
  ipAddress: z.string().trim().max(64).optional(),
  userAgent: z.string().trim().max(512).optional(),
  failureReason: z.string().trim().max(200).optional(),
}).omit({
  id: true,
  createdAt: true,
});

export type LoginHistoryInsert = z.infer<typeof loginHistoryInsertSchema>;

/**
 * Inviting a Worker.
 *
 * No password field, and there never will be one. ADR-008 Decision 2: the CRM
 * must never own a password, so a form that could accept one must not exist.
 */
export const inviteUserSchema = z.object({
  email: z
    .string()
    .trim()
    .toLowerCase()
    .min(1, "Email is required")
    .email("Enter a valid email address"),
  name: z.string().trim().min(1, "Name is required").max(120),
  role: z.enum(["super_admin", "worker"]),
});

export type InviteUserInput = z.infer<typeof inviteUserSchema>;

/** Changing a role. Separated so a profile edit cannot carry one. */
export const changeRoleSchema = z.object({
  role: z.enum(["super_admin", "worker"]),
});

export const changeStatusSchema = z.object({
  status: z.enum(["active", "suspended", "disabled"]),
});

export type UserSelect = z.infer<typeof userSelectSchema>;
export type UserInsert = z.infer<typeof userInsertSchema>;
export type UserUpdate = z.infer<typeof userUpdateSchema>;
