export {
  AppError,
  ConfigurationError,
  ConflictError,
  DatabaseError,
  ExternalServiceError,
  ForbiddenError,
  NotFoundError,
  UnauthorizedError,
  UnexpectedError,
  ValidationError,
  isAppError,
  toAppError,
  type AppErrorOptions,
  type ErrorSeverity,
} from "./app-error";
